using FinancialMcp.Domain.Entities;
using FinancialMcp.Domain.Enums;
using FluentAssertions;
using Xunit;

namespace FinancialMcp.Application.Tests;

/// <summary>
/// Card #14 — <see cref="Transaction.NeedsConfirmation"/>, the per-status transition
/// timestamps set by <see cref="Transaction.TransitionTo"/>, and the
/// <c>Confirmed</c>-only <see cref="Transaction.IsEligibleForActualSpend"/> gate.
/// </summary>
public class TransactionTests
{
    private static readonly DateOnly Today = new(2026, 9, 2);

    [Fact]
    public void NeedsConfirmation_is_true_for_a_scheduled_transaction_with_a_past_expected_date()
    {
        var t = new Transaction { Status = TransactionStatus.Scheduled, ExpectedDate = Today.AddDays(-1) };

        t.NeedsConfirmation(Today).Should().BeTrue();
    }

    [Fact]
    public void NeedsConfirmation_is_false_for_a_scheduled_transaction_expected_today()
    {
        var t = new Transaction { Status = TransactionStatus.Scheduled, ExpectedDate = Today };

        t.NeedsConfirmation(Today).Should().BeFalse();
    }

    [Fact]
    public void NeedsConfirmation_is_false_for_a_scheduled_transaction_expected_in_the_future()
    {
        var t = new Transaction { Status = TransactionStatus.Scheduled, ExpectedDate = Today.AddDays(1) };

        t.NeedsConfirmation(Today).Should().BeFalse();
    }

    [Theory]
    [InlineData(TransactionStatus.Revision)]
    [InlineData(TransactionStatus.Confirmed)]
    public void NeedsConfirmation_is_false_for_a_non_scheduled_transaction_even_when_overdue(TransactionStatus status)
    {
        var t = new Transaction { Status = status, ExpectedDate = Today.AddDays(-10) };

        t.NeedsConfirmation(Today).Should().BeFalse();
    }

    [Fact]
    public void TransitionTo_Scheduled_stamps_only_ScheduledAt()
    {
        var now = DateTimeOffset.UtcNow;
        var t = new Transaction();

        t.TransitionTo(TransactionStatus.Scheduled, now);

        t.Status.Should().Be(TransactionStatus.Scheduled);
        t.ScheduledAt.Should().Be(now);
        t.ConfirmedAt.Should().BeNull();
        t.SubmittedForReviewAt.Should().BeNull();
    }

    [Fact]
    public void TransitionTo_Confirmed_stamps_only_ConfirmedAt()
    {
        var now = DateTimeOffset.UtcNow;
        var t = new Transaction();

        t.TransitionTo(TransactionStatus.Confirmed, now);

        t.Status.Should().Be(TransactionStatus.Confirmed);
        t.ConfirmedAt.Should().Be(now);
        t.ScheduledAt.Should().BeNull();
        t.SubmittedForReviewAt.Should().BeNull();
    }

    [Fact]
    public void TransitionTo_Revision_never_stamps_SubmittedForReviewAt()
    {
        // SubmittedForReviewAt is only ever copied from transaction_revisions.CreatedAt on
        // approval — it must never be regenerated by a plain status transition.
        var t = new Transaction();

        t.TransitionTo(TransactionStatus.Revision, DateTimeOffset.UtcNow);

        t.Status.Should().Be(TransactionStatus.Revision);
        t.SubmittedForReviewAt.Should().BeNull();
        t.ScheduledAt.Should().BeNull();
        t.ConfirmedAt.Should().BeNull();
    }

    [Fact]
    public void TransitionTo_does_not_overwrite_a_timestamp_already_set()
    {
        var firstScheduled = new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);
        var t = new Transaction();

        t.TransitionTo(TransactionStatus.Scheduled, firstScheduled);
        t.TransitionTo(TransactionStatus.Confirmed, firstScheduled.AddMonths(1));
        t.TransitionTo(TransactionStatus.Scheduled, firstScheduled.AddMonths(2)); // reverted later

        t.ScheduledAt.Should().Be(firstScheduled, "the first Scheduled entry wins");
        t.ConfirmedAt.Should().Be(firstScheduled.AddMonths(1));
    }

    [Theory]
    [InlineData(TransactionStatus.Revision, false)]
    [InlineData(TransactionStatus.Scheduled, false)]
    [InlineData(TransactionStatus.Confirmed, true)]
    public void IsEligibleForActualSpend_only_counts_Confirmed_expenses(TransactionStatus status, bool expected)
    {
        var t = new Transaction { Status = status, Type = TransactionType.Expense };

        t.IsEligibleForActualSpend.Should().Be(expected);
    }
}
