using System.ComponentModel;
using FinancialMcp.Application.BalanceProjection.GetBalanceProjection;
using MediatR;
using ModelContextProtocol.Server;

namespace FinancialMcp.Api.Mcp.Tools;

[McpServerToolType]
public sealed class BalanceProjectionTools(IMediator mediator)
{
    [McpServerTool(Name = "get_balance_projection"), Description(
        """
        Projects month-by-month credit-card bill totals for a checking account, consolidating
        the billing cycle, installment plans, and fixed monthly entries of every credit card
        whose bill is paid from that account (CLAUDE.md > Business Rules > Credit card).

        ## Parameters
        - **accountId** — `Guid` of the checking account to project. Required. Matches
          `CreditCard.PaymentAccountId` — every credit card paid from this account is
          included automatically; there's no separate card selector.
        - **monthsAhead** — Number of future months to include, starting from the current
          month. Optional, defaults to `6`.

        ## Behavior
        - Read-only; does not modify any data or import anything.
        - For each projected month, three kinds of entries are combined:
          1. **Existing statement entries** — rows already imported with an `InvoiceDueDate`
             (`Venc. Fatura`) falling in that month, used as-is.
          2. **Remaining installments** — for `Recurrence = Installment` entries, generates
             the not-yet-imported installments (`currentInstallment+1` through
             `totalInstallments`), one per month, same amount/description, until the plan
             is exhausted. Never duplicates an installment already present in the statement.
          3. **Fixed monthly entries** — `Recurrence = FixedMonthly` rows repeat every month
             indefinitely (no end date is modeled) unless a matching entry already exists
             for that month.
        - Each month's entries are consolidated into a single total bill amount and a single
          payment date — mirroring the real-world rule that a card's bill hits the checking
          account as one lump "Pagamento de cartão" entry, never as separate line items.
        - The payment date is the latest entry date in that month, rolled forward to the next
          business day if it falls on a Saturday or Sunday (`BusinessDayHelper.NextBusinessDay`).
        - A card qualifies for inclusion purely by having `PaymentAccountId == accountId` —
          not by a separately-stored transaction flag — so this is always in sync with the
          actual `CreditCard` records returned by `list_credit_cards`.

        ## Example
        ```json
        { "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "monthsAhead": 3 }
        ```

        ## Returns
        A list of `MonthlyProjectionDto` (year, month, entries, totalCardBills,
        cardPaymentDate) — one entry per projected month, each `entries` item being a
        `ProjectedEntryDto` (description, amount, entryDate, projected, installmentLabel).
        `projected = false` means the entry is already in the statement; `true` means it was
        generated by this projection (a future installment or a repeated fixed entry).
        """)]
    public Task<IReadOnlyList<MonthlyProjectionDto>> GetBalanceProjectionAsync(
        Guid accountId, int monthsAhead = 6, CancellationToken cancellationToken = default) =>
        mediator.Send(new GetBalanceProjectionQuery(accountId, monthsAhead), cancellationToken);
}
