using MediatR;

namespace FinancialMcp.Application.BalanceProjection.GetBalanceProjection;

/// <summary>
/// Corresponds to the MCP tool `get_balance_projection`. Generates the balance projection
/// consolidated by applying the billing cycle, installment plans, and recurring entries
/// (see CLAUDE.md > Business Rules > Credit card).
/// </summary>
/// <remarks>Handler returns a read-only list of MonthlyProjectionDto, with one entry per month in the requested
/// horizon.</remarks>
/// <param name="AccountId">Identifier of the account to project balances for.</param>
/// <param name="MonthsAhead">Number of future months to include in the projection; defaults to 6.</param>
public sealed record GetBalanceProjectionQuery(Guid AccountId, int MonthsAhead = 6)
    : IRequest<IReadOnlyList<MonthlyProjectionDto>>;

/// <summary>
/// Monthly projection of financial entries including the total card bill and an optional card payment date.
/// </summary>
/// <remarks>Immutable data transfer object intended for read-only use in reporting and UI models.</remarks>
/// <param name="Year">Calendar year of the projection.</param>
/// <param name="Month">Month of the projection (1-12).</param>
/// <param name="Entries">Read-only list of projected entries for the month.</param>
/// <param name="TotalCardBills">Total amount of the card bill for the month.</param>
/// <param name="CardPaymentDate">Date when the card payment is scheduled, or null if not set.</param>
public sealed record MonthlyProjectionDto(
    int Year,
    int Month,
    IReadOnlyList<ProjectedEntryDto> Entries,
    decimal TotalCardBills,
    DateOnly? CardPaymentDate);

/// <summary>
/// Represents a projected ledger entry for forecasting or fixed future installments.
/// </summary>
/// <param name="Description">Human-readable description of the entry.</param>
/// <param name="Amount">Monetary amount of the entry.</param>
/// <param name="EntryDate">Date of the entry (DateOnly).</param>
/// <param name="Projected">True when generated by projection (future or fixed installment) and not yet present in the statement.</param>
/// <param name="InstallmentLabel">Optional installment label, for example "7/12".</param>
public sealed record ProjectedEntryDto(
    string Description,
    decimal Amount,
    DateOnly EntryDate,
    bool Projected,
    string? InstallmentLabel);
